### ISSUE TITLE
 System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by kiquenet** [mixerp/MixERP.Net.VCards#20]
Test method TestsUnitarios.TestsVCF.Leer_Vcard_Contactos threw exception: 
    System.ArgumentException: An item with the same key has already been added.
  
Don't work: TEL;TYPE=WORK;TYPE=PREF:6xx-xxx-xxx

Work: TEL;TYPE=CELL:6xx-xxx-xxx

Test Name:	Leer_Vcard_Contactos
Test Outcome:	Failed
Result StackTrace:	
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at MixERP.Net.VCards.Parser.TokenParser.GetAdditionalKeyMembers(String data)
   at MixERP.Net.VCards.Parser.TokenParser.GetToken(String line)
   at MixERP.Net.VCards.Parser.TokenParser.Parse(String contents)
   at MixERP.Net.VCards.Deserializer.GetVCard(String contents)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MixERP.Net.VCards.Deserializer.GetVCards(String contents)
   at TestsUnitarios.TestsVCF.Leer_Vcard_Contactos() in 
   \GMailManager\Tests\TestsUnitarios\TestsVCF.cs:line 37
Result Message:	

System.ArgumentException: An item with the same key has already been added.

**Comment by seanmcne** [comment]
I'm running into the same issue :(

**Comment by sanketshahane05** [comment]
Same issue {"An item with the same key has already been added."}

**Comment by mahmoodyali** [comment]
I'm running into the same issue :(
